image: maven:3.9.4-eclipse-temurin-17-alpine

cache:
  key: "${CI_PROJECT_NAME}"
  paths:
    - .sonar/cache
    - .m2
    - bar/target
    - diner/target
    - front/target
    - kitchen/target

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

stages:
  - build
  - test
  - qa
  - docker

build:
  stage: build
  only:
      variables:
          # Run only when commit message doesn't start with "DinerRelease"
        - $CI_COMMIT_MESSAGE !~ /^DinerRelease.*/    
  script:
    - mvn -Dgitlab-ci compile -B

test:
  stage: test
  services:
    - rabbitmq:3.12.4-alpine
  only:
      variables:
          # Run only when commit message doesn't start with "DinerRelease"
        - $CI_COMMIT_MESSAGE !~ /^DinerRelease.*/    
  script:
    - mvn -Dspring.profiles.active=gitlab,non-async -Dgitlab-ci verify -B
  artifacts:
    reports:
      junit:
        - bar/target/surefire-reports/TEST-*.xml
        - diner/target/surefire-reports/TEST-*.xml
        - kitchen/target/surefire-reports/TEST-*.xml
        - front/target/surefire-reports/TEST-*.xml

sonar:
  stage: qa
  only:
    variables:
          # Run only when commit message doesn't start with "DinerRelease"
        - $CI_COMMIT_MESSAGE !~ /^DinerRelease.*/  
  script:
    - mvn -Dgitlab-ci -Dsonar.java.source=17 org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar -B

docker:
  stage: docker
  script:
    - mvn docker:build -Pdocker -Dmaven.test.skip=true
    - mvn docker:push -Pdocker -Ddocker.registry=registry.tjonahen.home:5000