image: maven:3.8.5-openjdk-17
 

cache:
  key: "${CI_PROJECT_NAME}"
  paths:
    - .sonar/cache
    - .m2
    - bar/target
    - diner/target
    - front/target
    - kitchen/target

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

stages:
  - build
  - test
  - qa

build:
  stage: build
  only:
      variables:
          # Run only when commit message doesn't start with "DinerRelease"
        - $CI_COMMIT_MESSAGE !~ /^DinerRelease.*/    
  script:
    - mvn clean compile -B

test:
  stage: test
  services:
    - rabbitmq:latest
  only:
      variables:
          # Run only when commit message doesn't start with "DinerRelease"
        - $CI_COMMIT_MESSAGE !~ /^DinerRelease.*/    
  script:
    - mvn -Dspring.profiles.active=gitlab verify -B
  artifacts:
    reports:
      junit:
        - bar/target/surefire-reports/TEST-*.xml
        - diner/target/surefire-reports/TEST-*.xml
        - kitchen/target/surefire-reports/TEST-*.xml
        - front/target/surefire-reports/TEST-*.xml

sonar:
  image: maven:3.8.5-openjdk-17
  stage: qa
  only:
    variables:
          # Run only when commit message doesn't start with "DinerRelease"
        - $CI_COMMIT_MESSAGE !~ /^DinerRelease.*/  
  script:
    - mvn -Dsonar.java.source=17 org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar -B

