openapi: 3.0.1
info:
  title: Bar REST API
  description: Bar REST API.
  termsOfService: n/a
  contact:
    name: J-Tech
    url: ordina.nl
    email: info@ordina.nl
  license:
    name: DBAD
    url: https://dbad-license.org/
  version: V1
  x-audience: company-internal
  x-api-id: fe011038-7a7c-40bb-a5c4-29c7533312b0
servers:
- url: //localhost:8080/
tags:
- name: bartender-controller
  description: Bartender Controller
paths:
  /api/menu:
    get:
      tags:
      - bartender-controller
      summary: get the posible drinks, aka the drinks menu
      operationId: getAllDrinksUsingGET
      responses:
        200:
          description: OK, get the current available drinks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Drink'
        404:
          description: If no drinks are available
          content: {}
      deprecated: false
  /api/order:
    post:
      tags:
      - bartender-controller
      summary: order drinks to be prepared
      operationId: orderUsingPOST
      requestBody:
        description: The ticket order, contains the bar tickets for a specific order.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketOrder'
        required: true
      responses:
        202:
          description: Accepted
          content: {}
      deprecated: false
      x-codegen-request-body-name: ticketOrder
components:
  schemas:
    TicketOrderItem:
      title: A single ticket item
      type: object
      properties:
        quantity:
          type: integer
          format: int64
        name:
          type: string
    TicketOrder:
      title: 'Ticket order, contains the drinks to be prepared (Tickets) and a reference
        to the order '
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TicketOrderItem'
        orderid:
          type: integer
          format: int64
    Drink:
      title: A beverage that is currently available.
      type: object
      properties:
        description:
          type: string
        name:
          type: string
        preparationTime:
          type: integer
          format: int64
        price:
          type: integer
          format: int64
